// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhmtfrslymcmzhqyvshn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobXRmcnNseW1jbXpocXl2c2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDUwOTIsImV4cCI6MjA3Mzg4MTA5Mn0.uSPAbwqVD3fdkSKDDZX8JHGDGg5KnFky4H9uZUas0T4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});